# Generated by Django 3.1.6 on 2021-11-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('barbero', 'Barbero'), ('cajero', 'Cajero')], default='barbero', max_length=20, verbose_name='position'),
        ),
    ]
