# Generated by Django 3.1.6 on 2021-12-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211110_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
